### ISSUE TITLE
track n trace user/password

### ISSUE THREAD

**Issue by Kifah** [dreipunktnull/dhl-shipment-tracking#1]
Hi.

In your documentation, you talk about having a track n tracker username&password.
Where would I get that? (exact link hopefully).
I have access to "Entwickler Portal/Developer Portal"

I tried using following values:
`
   $cig_user = 'my_developer_user_id';
   $cig_password = 'my_developer_password';

   $tnt_user = 'dhl_entwicklerportal';
   $tnt_password = 'Dhl_123';

   $credentials = new DreiCredentials($cig_user, $cig_password, 
   DreiCredentials::ENDPOINT_SANDBOX, $tnt_user, $tnt_password);

   $api = new ShipmentTracking($credentials);

   $result = $api->getPiece('00340434161094042557', RequestBuilder::LANG_EN);
   echo "just a test";

`

But as a result value I get

`<?xml version="1.0" encoding="UTF-8"?>
<data name="piece-shipment-list" request-id="e0728416-56c8-4f6a-b891-c1d6ee904728" code="5" error="Log-in failed">
    <data name="piece-shipment" searched-piece-code="00340434161094042557" piece-code="00340434161094042557" piece-id="" recipient-name="" recipient-street="" recipient-city="" status="" short-status="" delivery-event-flag="" division="" recipient-id="" product-code="" product-key="" product-name="" international-flag="0" piece-status="5" piece-status-desc="Log-in failed"/>
</data>`

**Comment by tabsl** [comment]
some more info: https://github.com/tabsl/dhl-shipment-tracking/blob/master/track.php#L6

**Comment by cedricziel** [comment]
Closing as this is in the current state of the project
