### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by panconjugo** [dreipunktnull/dhl-shipment-tracking#4]
Hi,

When I run: 

`composer require dreipunktnull/dhl-shipment-tracking`

I get this error:

 ```
[InvalidArgumentException]
  Could not find a version of package dreipunktnull/dhl-shipment-tracking matching your minimum-stability (stable). R
  equire it with an explicit version constraint allowing its desired stability.
```

How can I solve this or bypass it?

Thanks.

**Comment by cedricziel** [comment]
There is no stable version that's tagged, yet.

You can either relax the constraints (you really should consult the composer documentation about that), or directly require `dreipunktnull/dhl-shipment-tracking:dev-master`.

**Comment by danielwagnerd** [comment]
Hi and thanks for your work,
do you think you can add versioning?
